cour.:
    resource: "@Cour_Bundle/Resources/config/routing.yml"
    prefix:   /cour



admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

Gestion_Cours:
    resource: "@Gestion_CoursBundle/Resources/config/routing.yml"
    prefix:   /admin/gestion-cour

gestion_blog:
    resource: "@Gestion_BlogBundle/Resources/config/routing.yml"
    prefix:   /admin/gestion-blog


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
